version: '3.7'

services:
  chatbot:
    image: rasa/rasa:1.10.10-full
    user: 1000:1000
 #   volumes:
 #     - /home/gioppo/Development/dockerfiles/micado_new/rasa:/app
    command:
#      - train
      - run
      - --cors
      - "*"
      - -p
      - "5005"
      - --enable-api
      - --auth-token
      - "thisismysecret"
    ports:
      - "5005:5005"
    volumes:
      - type: volume
        source: chatbot_data
        # target is the path in the container
        target: /app
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - micado_net

  action_server:
    image: rasa/rasa-sdk:1.10.2
    volumes:
      - type: volume
        source: chatbot_action
        # target is the path in the container
        target: /app/actions
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - micado_net

  duckling_server:
    image: rasa/duckling:0.1.6.3
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - micado_net
    

volumes:
  chatbot_data:
    driver: local
    driver_opts:
      type: none
      # device is the path in the host that has to be absolute
      device: $PWD/rasa
      o: bind
  chatbot_action:
    driver: local
    driver_opts:
      type: none
      # device is the path in the host that has to be absolute
      device: $PWD/rasa/actions
      o: bind

networks:
  micado_net:
#    driver: bridge
    external: true
